Add vcs-browser and contribute URL type
ximion/appstream pull request #392
Opened 2022-03-23 18:16 UTC by JakobDev

This PR adds vcs-browser and contribute as URL types as in #374. It was easier and cleaner to make a new PR than to update the old one.

2022-03-29 18:51 UTC, ximion requested changes
Looks good to me, except for the VCS enum name that should go after its string representation, for clarity.

2022-03-29 18:51 UTC, ximion commented on src/as-enums.h
> +	AS_URL_KIND_VCS,
This should be `AS_URL_KIND_VCS_BROWSER` shouldn't it?

2022-03-29 20:15 UTC, JakobDev commented
I had now replaced AS_URL_KIND_VCS with AS_URL_KIND_VCS_BROWSER

2022-03-29 20:41 UTC, ximion approved these changes

2022-03-29 20:42 UTC, merged

2022-03-29 20:42 UTC, ximion commented
Looks good now, thank you for the patch! :-)

2022-03-29 21:11 UTC, JakobDev commented
I informed [GNOME](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1702) and [KDE](https://bugs.kde.org/show_bug.cgi?id=452054) that the new types has been added. Would be nice, if you can create a new release. It will take some time until the distros ship the new Version, so the Implementation in the Software Centers can be started.

2022-03-30 01:38 UTC, cassidyjames commented
Thanks @JakobDev, I'll file the appropriate issues on elementary software.