Add validation for content_rating
ximion/appstream pull request #486
Opened 2023-04-13 14:05 UTC by JakobDev

This PR adds a validation for` content_rating`. I needed to add 2 functions to `as-content-rating.c` and make `OarsVersio`n public. I also added a new helper function which checks if a string is null or empty.

2023-04-16 20:35 UTC, ximion requested changes

2023-04-16 20:35 UTC, ximion commented on src/as-utils-private.h
> +#define as_str_empty(str) (str == NULL || str[0] == '\0')
Please use `as_is_empty` instead.

2023-04-16 20:35 UTC, ximion commented on src/as-content-rating.h
> +gboolean	as_content_rating_value_is_valid (const gchar *id, AsContentRatingValue value);
Please don't add those as public API, make them internal API instead. Put functions like this in `as-content-rating-private.h` and you should be fine, same for the enums.

2023-04-21 13:58 UTC, JakobDev commented
The changes are now done! I also added a check for duplicates.

2023-04-24 20:52 UTC, ximion requested changes
I had a bunch more remarks, mostly copy pasta issues though.

I do however wonder, since this is quite a substantial addition, whether it's worth to add a small test for this to the testsuite in `test-validate.c`.

2023-04-24 20:52 UTC, ximion commented on src/as-validator.c
> +			as_validator_check_content_rating(validator, iter);
```suggestion
			as_validator_check_content_rating (validator, iter);
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator.c
> +	if (as_is_empty(oars_type)) {
```suggestion
	if (as_is_empty (oars_type)) {
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator.c
> +		if (!as_is_oars_key(id, oars_version)) {
```suggestion
		if (!as_is_oars_key (id, oars_version)) {
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator.c
> +		if (as_is_empty(value_data)) {
```suggestion
		if (as_is_empty (value_data)) {
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator.c
> +		content_rating = as_content_rating_value_from_string(value_data);
```suggestion
		content_rating = as_content_rating_value_from_string (value_data);
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator.c
> +		if (!as_content_rating_value_is_valid(id, content_rating)) {
```suggestion
		if (!as_content_rating_value_is_valid (id, content_rating)) {
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator-issue-tag.h
> +	  N_("The  `type ` attribute of the  `content_rating` is missing or empty."),
```suggestion
	  N_("The  `type` attribute of this `content_rating` element is missing or empty."),
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator-issue-tag.h
> +	  N_("The  `type ` attribute of the  `content_rating` has a invalid value."),
```suggestion
	  N_("The  `type` attribute of the `content_rating` element has a invalid value."),
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator-issue-tag.h
> +	  N_("The  `id ` attribute of the  `content_attribute` is missing or empty."),
```suggestion
	  N_("The  `id` attribute of the `content_attribute` element is missing or empty."),
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator-issue-tag.h
> +	  N_("The  `id ` attribute of the  `content_attribute` has a invalid value."),
```suggestion
	  N_("The  `id` attribute of the `content_attribute` element has a invalid value."),
```

2023-04-24 20:52 UTC, ximion commented on src/as-validator-issue-tag.h
> +	  N_("An `content_attribute` tag with this id has already been defined."),
```suggestion
	  N_("A `content_attribute` tag with this ID has already been defined."),
```

2023-04-24 20:52 UTC, ximion commented on src/as-content-rating.c
> + * Returns: a #AsOarsVersion or %AS_OARS_VERSION_UNKNWON for unknown
```suggestion
 * Returns: a #AsOarsVersion or %AS_OARS_VERSION_UNKNOWN for unknown
```

2023-04-24 20:52 UTC, ximion commented on src/as-content-rating-private.h
> +	AS_OARS_VERSION_UNKNOWN
The UNKNOWN version must be at the first position, to ease future extension.

2023-04-24 20:52 UTC, ximion commented on src/as-content-rating.c
> + * Since: 1.0
Please drop the "Since" line, since this is internal API now (and it will make backporting the patch easier).

2023-04-24 20:52 UTC, ximion commented on src/as-content-rating.c
> + * Since: 1.0
Please drop the "Since" line, since this is internal API now (and it will make backporting the patch easier).

2023-04-26 18:38 UTC, ximion commented
There's a bunch of minor formatting issues that aren't (yet) addressed ;-)

2023-04-26 18:39 UTC, ximion commented on src/as-content-rating.c
> + * Since: 1.0
Not needed, since this is private API (for now...).

2023-04-28 09:44 UTC, JakobDev commented
Should be all done now

2023-05-12 06:07 UTC, JakobDev commented
Ping @ximion

2023-05-14 15:20 UTC, ximion commented
Looks good, except for some minor nitpicks that I'll fix post-merge.
Thank you for the patch and sorry for the long delay, I have a lot on my plate right now.

2023-05-14 15:21 UTC, merged