Add FreeBSD CI using Cirrus CI.
ximion/appstream pull request #520
Opened 2023-09-01 10:23 UTC by arrowd

Testing is omitted for the moment because AsMonitor tests fail due to FreeBSD-specific bug in glib: https://gitlab.gnome.org/GNOME/glib/-/issues/576

I might also miss some dependencies, so the commit might need amending after the repository enables Cirrus CI.

Obsoletes https://github.com/ximion/appstream/pull/485 PR

2023-10-17 22:56 UTC, ximion commented
To make this a bit more maintainable, would it be possible to make Cirrus call `tests/ci/run-build.sh` and use different build options of *BSD? Or does FreeBSD not support `/etc/os-release`, so adding support for it would be more tedious in that file? (it would be nice to configure all CI builds in one place...)

2023-10-18 13:26 UTC, arrowd commented
Sure, it seems we can reuse that.

2023-10-30 17:29 UTC, ximion requested changes

2023-10-30 17:29 UTC, ximion commented on .cirrus-ci.yml
> +    - sed -i '' "s/'-i'/'-i \"\"'/" src/meson.build
Is this still needed?

2023-10-30 17:48 UTC, arrowd commented
I see you changed this line 2 weeks ago. I guess, no it shouldn't be needed now.

2023-10-30 22:06 UTC, ximion commented
Good! I guess this will not actually build before I merge it, so let's merge it now and hopefully it will be fine (I will probably need you to address any non-obvious issues, as I am less familiar with FreeBSD).

2023-10-30 22:07 UTC, merged

2023-10-30 22:28 UTC, ximion commented
Looks like that build environment has no C compiler. Can you please fix that?