fix as-system-info compilation on mac
ximion/appstream pull request #526
Opened 2023-09-09 02:25 UTC by alex-tee

It looks like it's the same logic as FreeBSD (Mac is based on BSD after all): https://stackoverflow.com/questions/583736/determine-physical-mem-size-programmatically-on-osx

(hopefully) fixes https://github.com/ximion/appstream/issues/519

2023-09-09 02:46 UTC, ximion commented
Have you tested this on macOS? Merging untested code is very iffy...

2023-09-09 08:15 UTC, alex-tee commented
I'm building my project in GitHub actions - please wait... will report back when I get this to work. For some reason Mac doesn't define uint/ushort/uchar even though it uses those in its own headers... very strange

2023-09-09 19:03 UTC, alex-tee commented
the current version of the PR passes compilation on mac and my software runs

2023-09-09 22:17 UTC, ximion commented
Does it also return a sensible value? This code doesn't have unit tests, for obvious reasons (mocking this would bypass the code we would want to test ^^).

2023-09-09 22:19 UTC, ximion commented on src/as-system-info.c
> +# ifdef __APPLE__
```suggestion
#ifdef __APPLE__
```
nit: no space after `#` please

2023-09-09 22:19 UTC, ximion commented on src/as-system-info.c
> +# endif
```suggestion
#endif
```

2023-09-16 07:18 UTC, alex-tee commented
> Does it also return a sensible value? This code doesn't have unit tests, for obvious reasons (mocking this would bypass the code we would want to test ^^).

I have no idea, sorry, I just needed this to build libadwaita. I don't have time to look too much into this, but my app with libadwaita seems to run fine

2023-09-23 02:42 UTC, ximion commented
> I have no idea, sorry, I just needed this to build libadwaita. I don't have time to look too much into this, but my app with libadwaita seems to run fine

Let's test this, it will be really easy to do!
Please create an XML file like this on your Mac:
```xml
<?xml version="1.0"?>
<component type="generic">
  <id>org.example.test</id>
  <name>TestApp</name>

  <requires>
    <memory>406900</memory>
  </requires>
</component>
``` 
I doubt your machine has 397 GiB RAM, in case it does, just increase the memory value a bit ;-)

Then use the freshly compiled `appstreamcli` and run this command:
`appstreamcli is-satisfied /path/to/your/dummy.xml` (replace the path to the just created XML file).
You should then see output like this:
```console
Relation check for: */*/*/org.example.test/*

Requirements:
 ✘ This software requires >= 397.36 GiB of memory, but this system has 30.48 GiB.
Recommendations:
 • No recommended items are set for this software.
Supported:
 • No supported items are set for this software.
``` 
If it gives the right amount of memory here, then everything is fine and we can merge this :-)

2023-09-24 03:30 UTC, ximion commented
Or even easier, just run `appstreamcli sysinfo` :-D

2023-10-02 17:07 UTC, dehesselle commented
Mac mini M1, macOS Monterey 12.7

Output from `LANG=C ./appstreamcli sysinfo`
```bash
Operating System Details:

(appstreamcli:73406): GLib-CRITICAL **: 19:02:03.203: g_utf8_strdown: assertion 'str != NULL' failed

(appstreamcli:73406): XbValueBindings-CRITICAL **: 19:02:03.203: xb_value_bindings_bind_str: assertion 'str != NULL' failed
? Unable to find operating system component '(null)'!

Kernel:
Name: Darwin
Version: 21.6.0

Hardware:
Physical Memory: 3577 MiB (3.49 GiB)

** (appstreamcli:73406): WARNING **: 19:02:03.203: Error while searching for modalias entries in /sys/devices: No such file or directory

User Input Controls:

** (appstreamcli:73406): WARNING **: 19:02:03.203: Unable to read input info: Unable to look for input device: AppStream was built without systemd-udevd support.
 ? console: yes
```
Output from `LANG=C ./appstreamcli is-satisfied test.xml`
```bash
Relation check for: */*/*/org.example.test/*

Requirements:
 ? This software requires >= 397.36 GiB of memory, but this system has 7.49 GiB.
Recommendations:
 ? No recommended items are set for this software.
Supported:
 ? No supported items are set for this software.
```

2023-10-02 17:15 UTC, ximion commented
That looks sane, I guess your Mac has 8GB of RAM?

2023-10-02 17:27 UTC, dehesselle commented
Oh I should have paid more attention. While I did notice that `sysinfo` shows a different value than the `is-satisfied` test and just chose to not bother, they're actually both wrong. The machine in question has 16 GB memory.

2023-10-02 22:37 UTC, ximion commented
So, apparently on macOS you are supposed to use `HW_MEMSIZE` and not `HW_PHYSMEM`, because the latter will give you nonsense values.
Apparently on macOS, physmem may be 32bit or may just give you "usable physical memory", instead of actual physical memory. Hurray... :-P

2023-10-02 23:26 UTC, dehesselle commented
That works! Outputs are now

```text
Operating System Details:

(appstreamcli:77778): GLib-CRITICAL **: 01:23:21.076: g_utf8_strdown: assertion 'str != NULL' failed

(appstreamcli:77778): XbValueBindings-CRITICAL **: 01:23:21.077: xb_value_bindings_bind_str: assertion 'str != NULL' failed
? Unable to find operating system component '(null)'!

Kernel:
Name: Darwin
Version: 21.6.0

Hardware:
Physical Memory: 16384 MiB (16.00 GiB)

** (appstreamcli:77778): WARNING **: 01:23:21.077: Error while searching for modalias entries in /sys/devices: No such file or directory

User Input Controls:

** (appstreamcli:77778): WARNING **: 01:23:21.077: Unable to read input info: Unable to look for input device: AppStream was built without systemd-udevd support.
 ? console: yes
```
and
```text
Relation check for: */*/*/org.example.test/*

Requirements:
 ? This software requires >= 397.36 GiB of memory, but this system has 16.00 GiB.
Recommendations:
 ? No recommended items are set for this software.
Supported:
 ? No supported items are set for this software.
```

2023-10-03 01:50 UTC, ximion commented
Perfect! @alex-tee, can you update the patch? We will need a new macOS-specific codepath for this and can't reuse the FreeBSD one.
I'd be happy to merge this patch then :-)

2023-10-03 01:50 UTC, ximion commented
Perfect! Thank you @dehesselle for testing this! @alex-tee, can you update the patch? We will need a new macOS-specific codepath for this and can't reuse the FreeBSD one.
I'd be happy to merge this patch then :-)

2023-10-03 01:51 UTC, ximion requested changes
Perfect! Thank you @dehesselle for testing this! @alex-tee, can you update the patch? We will need a new macOS-specific codepath for this and can't reuse the FreeBSD one.
I'd be happy to merge this patch then :-)

2023-10-16 22:34 UTC, ximion commented
Ping?

2023-10-17 22:42 UTC, ximion commented
@dehesselle Can you please check if the current changes in Git master compile and work on macOS? Potentially parts of this PR are still needed...

2023-10-18 00:38 UTC, dehesselle commented
This is the first time I'm building `master`. While the `as-system-info` problem of this PR is fixed and appstream builds fine, I cannot build `libadwaita` with it:

```
../../../usr/src/libadwaita-1.4.0/src/adw-about-window.c:2007:14: error: implicit declaration of function 'as_component_get_releases' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  releases = as_component_get_releases (component);
             ^
../../../usr/src/libadwaita-1.4.0/src/adw-about-window.c:2007:14: note: did you mean 'as_component_set_releases'?
../../../include/appstream/as-component.h:289:13: note: 'as_component_set_releases' declared here
void           as_component_set_releases (AsComponent *cpt, AsReleaseList *releases);
               ^
../../../usr/src/libadwaita-1.4.0/src/adw-about-window.c:2007:12: warning: incompatible integer to pointer conversion assigning to 'GPtrArray *' (aka 'struct _GPtrArray *') from 'int' [-Wint-conversion]
  releases = as_component_get_releases (component);
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../usr/src/libadwaita-1.4.0/src/adw-about-window.c:2041:20: error: implicit declaration of function 'as_component_get_developer_name' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  developer_name = as_component_get_developer_name (component);
                   ^
../../../usr/src/libadwaita-1.4.0/src/adw-about-window.c:2041:20: note: did you mean 'as_component_get_developer'?
../../../include/appstream/as-component.h:248:15: note: 'as_component_get_developer' declared here
AsDeveloper  *as_component_get_developer (AsComponent *cpt);
              ^
../../../usr/src/libadwaita-1.4.0/src/adw-about-window.c:2041:18: warning: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
  developer_name = as_component_get_developer_name (component);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
```

I'm assuming that `libadwaita` as a downstream project will have to adopt to these changes later, but in the meantime I'd like for this commit to be backported to 0.16.x so I can use a (persumably) 0.16.4 in my builds at some point.

2023-10-18 00:46 UTC, ximion commented
Right. This should be backportable, but Adwaita can also surely be made to build with any AppStream version. Thanks for confirming this works! :-)

2023-10-18 00:46 UTC, closed without merging